version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: shopping-mysql
    environment:
      MYSQL_ROOT_PASSWORD: shopping123!
      MYSQL_DATABASE: shopping_mall
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shopping-network
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: shopping-backend
    environment:
      - MYSQL_ROOT_PASSWORD=shopping123!
      - MYSQL_DATABASE=shopping_mall
      - MYSQL_HOST=shopping-mysql
      - SECRET_KEY=rocky-shopping-secret-key-2024
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - shopping-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - API_URL=http://localhost:8000
        - GOOGLE_AUTH_CLIENT_ID="본인 구글 클라이언트 ID"
    container_name: shopping-frontend
    ports:
      - "3000:3000"
    networks:
      - shopping-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: shopping-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - shopping-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  shopping-network:
    driver: bridge